backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: img

collections:
  - name: "posts"
    label: "posts"
    folder: 'posts'
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Message", name: "message", widget: "string" }